// <auto-generated />
using CalculadoraCustos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculadoraCustos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class CalculadoraCustosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculadoraCustos.Domain.Models.ItemFichaTecnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PratoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoBaseId")
                        .HasColumnType("int");

                    b.Property<double>("QuantidadeUtilizada")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PratoId");

                    b.HasIndex("ProdutoBaseId");

                    b.ToTable("ItensFicaTecnica");
                });

            modelBuilder.Entity("CalculadoraCustos.Domain.Models.Prato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pratos");
                });

            modelBuilder.Entity("CalculadoraCustos.Domain.Models.ProdutoBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoEmbalagem")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("QuantidadeEmbalagem")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProdutosBase");
                });

            modelBuilder.Entity("CalculadoraCustos.Domain.Models.ItemFichaTecnica", b =>
                {
                    b.HasOne("CalculadoraCustos.Domain.Models.Prato", "Prato")
                        .WithMany("Ingredientes")
                        .HasForeignKey("PratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalculadoraCustos.Domain.Models.ProdutoBase", "ProdutoBase")
                        .WithMany()
                        .HasForeignKey("ProdutoBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prato");

                    b.Navigation("ProdutoBase");
                });

            modelBuilder.Entity("CalculadoraCustos.Domain.Models.Prato", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
